name: rnamigos
channels:
  - soumith
  - rdkit
  - openbabel
  - conda-forge
  - defaults
dependencies:
  - _pytorch_select=0.1
  - _tflow_select=2.3.0
  - absl-py=0.9.0
  - appnope=0.1.0
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - attrs=20.1.0
  - backcall=0.2.0
  - biopython=1.77
  - blas=1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.7.22
  - cairo=1.14.12
  - certifi=2020.6.20
  - cffi=1.14.2
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - cryptography=3.1
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.25.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - flask=1.1.2
  - fontconfig=2.13.0
  - freetype=2.10.2
  - gast=0.2.2
  - gettext=0.19.8.1
  - glib=2.65.0
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - itsdangerous=1.1.0
  - jedi=0.17.1
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - lcms2=2.11
  - libboost=1.67.0
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libxml2=2.9.10
  - llvm-openmp=10.0.0
  - lz4-c=1.9.2
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - networkx=2.5
  - nglview=1.2.2
  - ninja=1.10.0
  - notebook=6.1.1
  - numpy=1.18.5
  - numpy-base=1.18.5
  - olefile=0.46
  - openbabel=2.4.1
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.40.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - prompt_toolkit=3.0.7
  - protobuf=3.12.3
  - ptyprocess=0.6.0
  - py-boost=1.67.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytorch=1.4.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.6
  - qtpy=1.9.0
  - rdkit=2019.03.1.0
  - readline=8.0
  - requests=2.24.0
  - scikit-image=0.16.2
  - scikit-learn=0.23.1
  - scipy=1.5.2
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.0.0
  - tensorflow=2.0.0
  - tensorflow-base=2.0.0
  - tensorflow-estimator=2.0.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.10.0
  - torchvision=0.2.1
  - tornado=6.0.4
  - tqdm=4.47.0
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - altair==4.1.0
    - appdirs==1.4.3
    - beautifulsoup4==4.9.0
    - bitarray==1.2.2
    - cython==0.29.16
    - dgl==0.4.1
    - forcelayout==1.0.6
    - forgi==2.0.2
    - future==0.17.1
    - h5py==2.9.0
    - isodate==0.6.0
    - logging-exceptions==0.1.8
    - multiset==2.1.1
    - nearpy==1.0.0
    - nx-altair==0.1.4
    - plyfile==0.7
    - pudb==2019.2
    - pycallgraph==1.0.1
    - rdflib==4.2.2
    - rnamigos==0.1
    - selenium==3.141.0
    - soupsieve==2.0
    - tb-nightly==1.15.0a20190711
    - tikzplotlib==0.9.3
    - torch-cluster==1.4.2
    - torch-geometric==1.2.1
    - torch-scatter==1.2.0
    - torch-sparse==0.4.0
    - urllib3==1.25.3
    - urwid==2.1.0
    - xlrd==1.2.0

